-- `users.email`'s original UNIQUE constraint is case-sensitive, which let
-- `foo@example.com` and `Foo@example.com` exist as two separate accounts —
-- the root cause of the case-variant-account ambiguity `org/members.rs`'s
-- `add_member` has to defend against with a fetch-all-and-refuse-to-guess
-- branch instead of a simple lookup. `POST /users` now normalizes to
-- lowercase before insert (see src/registration.rs), so this constraint
-- enforces the same invariant at the database level for defense in depth.
--
-- Uses a separate unique index rather than replacing the column-level
-- UNIQUE, since dropping the auto-named constraint requires knowing its
-- generated name and this is simpler and equally effective.
CREATE UNIQUE INDEX users_email_lower_idx ON users (lower(email));
