name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      pull-requests: read
      checks: write
      packages: write
    uses: oxHive/pipelines/.github/workflows/rust-release.yml@main
    with:
      package-name: wardn
      binary-name: wardn
      publish-homebrew: true
      homebrew-install: 'bin.install "wardn"'
      publish-docker: true
    secrets: inherit
